name: Remote SSH Command to EC2
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands on EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MLOPS_SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.MLOPS_SERVER_KEY }}
          script: |
            cd ~/mlops-project/mlops-house-project
            git pull 
            source .venv/bin/activate
            cd src
            python run_experiment_pipeline.py
